name: aamva_parser
description: Scans an AAMVA drivers license
version: 0.0.1
author: Martin Wallace

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
